service: serverless-http-api-typescript
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    SUPABASE_KEY: ${env:SUPABASE_KEY}
    SUPABASE_URL: ${env:SUPABASE_URL}
functions:
  hello:
    handler: feedback/getFeedback
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
