service: serverless-http-api-typescript
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    SUPABASE_KEY: ${process.env.SUPABASE_KEY}
    SUPABASE_URL: ${process.env.SUPABASE_URL}
functions:
  hello:
    handler: lambdas/feedback.feedback
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
