service: feedback-api
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  stage: dev
  region: ap-southeast-2
  runtime: nodejs14.x
  httpApi:
    payload: "1.0"
    cors: true
    authorizers:
      cognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: ${env:COGNITO_ISSUER_URL}
        audience:
          - ${env:COGNITO_CLIENT_ID}
  environment:
    SUPABASE_KEY: ${env:SUPABASE_KEY}
    SUPABASE_URL: ${env:SUPABASE_URL}
functions:
  getFeedback:
    handler: lambdas/feedback.getFeedback
    events:
      - httpApi:
          path: /
          method: get

  addFeedback:
    handler: lambdas/feedback.addFeedback
    events:
      - httpApi:
          path: /
          method: post
          authorizer:
            name: cognitoAuthorizer

  deleteFeedback:
    handler: lambdas/feedback.deleteFeedback
    events:
      - httpApi:
          path: /{id}
          method: delete
          authorizer:
            name: cognitoAuthorizer

plugins:
  - serverless-plugin-typescript
