service: feedback-api
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  stage: dev
  region: ap-southeast-2
  runtime: nodejs14.x
  environment:
    SUPABASE_KEY: ${env:SUPABASE_KEY}
    SUPABASE_URL: ${env:SUPABASE_URL}
functions:
  getFeedback:
    handler: lambdas/feedback.getFeedback
    events:
      - httpApi:
          path: /
          method: get
  addFeedback:
    handler: lambdas/feedback.addFeedback
    events:
      - httpApi:
          path: /
          method: post

plugins:
  - serverless-plugin-typescript
