name: Deploy APIs
on:
  push:
    branches:
      - master
env:
  AWS_REGION: ap-southeast-2
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  SUPABASE_KEY: "${{ secrets.SUPABASE_KEY }}"
  SUPABASE_URL: "${{ secrets.SUPABASE_URL }}"
  COGNITO_ISSUR_URL: "${{ secrets.COGNITO_ISSUER_URL }}"
  COGNITO_CLIENT_ID: "${{ secrets.COGNITO_CLIENT_ID }}"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ env.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ env.AWS_SECRET_ACCESS_KEY }}"
          aws-region: "${{ env.AWS_REGION }}"

      - name: Build Serverless service
        run: npm install
        working-directory: ./api

      - name: Deploy Serverless service
        run: npx serverless deploy
        working-directory: ./api
        env:
          SUPABASE_KEY: "${{ secrets.SUPABASE_KEY }}"
          SUPABASE_URL: "${{ secrets.SUPABASE_URL }}"
